### PR TITLE
Fully delegate installation to rstantools

### PR DESCRIPTION
**Pull request by andrjohns**
This PR updates your package to fully delegate the installation/compilation of stan models to rstantools. 

There were also several test/check errors due to a missing `offset` argument to the `predict` function, so I've also added default zero values to those calls so that the checks & tests pass

### CODE REVIEW

**Comment by seananderson** [comment]
Thanks @andrjohns! I'll get a version off to CRAN shortly.

**Comment by bgoodri** [comment]
We need this merged PR to be released to CRAN in order to release the StanHeaders that has been years in the making but is still years behind the current Stan development branch. Please do so this week.

**Comment by seananderson** [comment]
Apologies. It was auto-rejected because of the note:

```
 * checking C++ specification ... NOTE
 Specified C++14: please drop specification unless essential
```

which I believe gets generated in the Makevars files by rstantools and I dropped the ball asking CRAN to consider this a false positive. I have replied to CRAN and will stay on top of this.

**Comment by andrjohns** [comment]
An updated version of rstantools was released today which should resolve that issue for you

**Comment by seananderson** [comment]
Thanks. I updated to the latest rstantools and sent to CRAN. I just got the "on its way to CRAN" reply now.

**Pull request merged**
